# Generated by Django 5.0.4 on 2024-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5', '0004_remove_customuser_is_agent_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('client', 'Клиент')], default='none', max_length=10, verbose_name='Роль'),
        ),
    ]
