# Generated by Django 5.1 on 2024-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0002_alter_property_address_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.CharField(max_length=100, null=True, verbose_name='Балкон'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(max_length=100, null=True, verbose_name='Санузел'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.FloatField(null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='property',
            name='city_district',
            field=models.CharField(max_length=100, null=True, verbose_name='Район города'),
        ),
        migrations.AddField(
            model_name='property',
            name='contract_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='property',
            name='coordinates',
            field=models.CharField(max_length=255, null=True, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_area',
            field=models.FloatField(null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.FloatField(null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_description',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(max_length=255, null=True, verbose_name='Микрорайон'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(null=True, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership',
            field=models.CharField(max_length=100, null=True, verbose_name='Собственность'),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='property',
            name='renovation',
            field=models.CharField(max_length=100, null=True, verbose_name='Ремонт'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_conditions',
            field=models.TextField(null=True, verbose_name='Условия продажи'),
        ),
        migrations.AddField(
            model_name='property',
            name='separate_rooms',
            field=models.IntegerField(null=True, verbose_name='Раздельных комнат'),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.FloatField(null=True, verbose_name='Общая площадь'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(null=True, verbose_name='Этажность'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_of_construction',
            field=models.IntegerField(null=True, verbose_name='Год постройки'),
        ),
    ]
