# Generated by Django 5.1 on 2024-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0010_alter_property_property_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Балкон'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Санузел'),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='property',
            name='communications',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Коммуникации'),
        ),
        migrations.AddField(
            model_name='property',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='property',
            name='documents',
            field=models.JSONField(blank=True, null=True, verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.BooleanField(default=False, verbose_name='Электричество'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Наличие мебели'),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип отопления'),
        ),
        migrations.AddField(
            model_name='property',
            name='house_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение участка'),
        ),
        migrations.AddField(
            model_name='property',
            name='layout',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Планировка'),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='property',
            name='loading_dock',
            field=models.BooleanField(default=False, verbose_name='Возможность разгрузки/погрузки'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.JSONField(blank=True, null=True, verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия продажи'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AddField(
            model_name='property',
            name='wall_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал стен'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к воде'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_of_construction',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
