# Generated by Django 5.1 on 2024-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0011_property_balcony_property_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ceiling_height',
        ),
        migrations.RemoveField(
            model_name='property',
            name='communications',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='property',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='property',
            name='electricity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='property',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_purpose',
        ),
        migrations.RemoveField(
            model_name='property',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='loading_dock',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sale_conditions',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='wall_material',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_access',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_of_construction',
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.CharField(default=123, max_length=20, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='building_section',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='property',
            name='room_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=1, verbose_name='Количество комнат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Населенный пункт или город'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Жилая'), ('non_residential', 'Нежилая'), ('commercial', 'Коммерческая')], max_length=20, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(verbose_name='Этажность дома'),
        ),
    ]
