# Generated by Django 5.1 on 2024-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0017_alter_apartment_balcony_alter_apartment_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproperty',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('one', 'Есть'), ('two', '2 санузла')], max_length=100, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='electricity',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('yes', 'Есть'), ('220v', '220В'), ('380v', '380В')], max_length=50, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='phone_lines',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6+')], null=True, verbose_name='Количество телефонов'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='property_type',
            field=models.CharField(choices=[('office', 'Офис'), ('retail_space', 'Торговое помещение'), ('free_space', 'Свободное помещение'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('food_service', 'Общепит'), ('business', 'Бизнес'), ('service_industry', 'Сфера услуг')], max_length=100, verbose_name='Вид недвижимости'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='renovation',
            field=models.CharField(blank=True, choices=[('good', 'Хороший'), ('normal', 'Нормальный'), ('poor', 'Плохое состояние'), ('no_finish', 'Без отделки'), ('construction_finish', 'Строительная отделка')], max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='water_supply',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('yes', 'Есть'), ('hot', 'Горячая'), ('cold', 'Холодная')], max_length=50, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6+')], verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('house', 'Дом'), ('cottage', 'Коттедж'), ('summer_house', 'Дача'), ('land_plot', 'Участок'), ('half_house', 'Полдома'), ('townhouse', 'Таунхаус')], max_length=20, verbose_name='Тип дома'),
        ),
        migrations.AlterField(
            model_name='house',
            name='renovation',
            field=models.CharField(blank=True, choices=[('elite_cottage', 'Элитный коттедж'), ('euro_finish', 'Евроотделка'), ('wood_finish', 'Отделка деревом'), ('not_finished', 'Не достроен')], max_length=100, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='house',
            name='wall_material',
            field=models.CharField(blank=True, choices=[('brick', 'Кирпичный'), ('panel', 'Панельный'), ('block_room', 'Блок-комнаты'), ('log', 'Бревенчатый'), ('monolithic_frame', 'Монолитно-каркасный'), ('silicate_blocks', 'Силикатные блоки')], max_length=100, verbose_name='Материал стен'),
        ),
    ]
