# Generated by Django 5.1 on 2024-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0003_remove_property_address_remove_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='balcony',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='property',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ceiling_height',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city_district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='kitchen_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='living_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='property',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='property',
            name='region',
        ),
        migrations.RemoveField(
            model_name='property',
            name='renovation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sale_conditions',
        ),
        migrations.RemoveField(
            model_name='property',
            name='separate_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='total_floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_of_construction',
        ),
        migrations.AddField(
            model_name='property',
            name='property_kind',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид недвижимости'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Жилая'), ('commercial', 'Коммерческая'), ('garage', 'Гараж')], max_length=20, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
    ]
