# Generated by Django 5.1 on 2024-08-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0004_remove_property_balcony_remove_property_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_kind',
            field=models.CharField(blank=True, choices=[], max_length=50, verbose_name='Вид недвижимости'),
        ),
    ]
