# Generated by Django 5.1 on 2024-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0015_remove_apartment_building_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Квартиру', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='commercialproperty',
            options={'verbose_name': 'Коммерскую невижимость', 'verbose_name_plural': 'Коммерческая недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Гараж', 'verbose_name_plural': 'Гаражи'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
