# Generated by Django 5.1 on 2024-08-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0016_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.CharField(blank=True, choices=[('balcony', 'Балкон'), ('none', 'Нет'), ('loggia', 'Лоджия'), ('balcony_and_loggia', 'Балкон и лоджия'), ('terrace', 'Терраса')], max_length=50, verbose_name='Балкон/лоджия'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('separate', 'Раздельный'), ('combined', 'Совмещенный'), ('two_or_more', '2 и более')], max_length=50, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, choices=[('euro', 'Евроремонт'), ('excellent', 'Отличный'), ('good', 'Хороший'), ('normal', 'Нормальный'), ('satisfactory', 'Удовлетворительный'), ('poor', 'Плохое состояние'), ('emergency', 'Аварийное состояние'), ('no_finish', 'Без отделки'), ('construction_finish', 'Строительная отделка')], max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6+')], verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='unit_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('room', 'Комната'), ('share_in_apartment', 'Доля в квартире')], max_length=50, verbose_name='Тип жилого объекта'),
        ),
    ]
