# Generated by Django 5.1 on 2024-08-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0018_alter_commercialproperty_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproperty',
            name='building_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, verbose_name='Класс здания'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='wall_material',
            field=models.CharField(blank=True, choices=[('block', 'Блочный'), ('panel', 'Панельный'), ('brick', 'Кирпичный'), ('monolithic', 'Монолитный')], max_length=100, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('one', 'Есть'), ('two', '2 санузла')], max_length=100, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='electricity',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('yes', 'Есть'), ('220v', '220В'), ('380v', '380В')], max_length=50, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='garage_type',
            field=models.CharField(choices=[('garage', 'Гараж'), ('parking_space', 'Машиноместо')], max_length=100, verbose_name='Тип гаража'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='renovation',
            field=models.CharField(blank=True, choices=[('good', 'Хороший'), ('normal', 'Нормальный'), ('poor', 'Плохое состояние'), ('no_finish', 'Без отделки'), ('construction_finish', 'Строительная отделка')], max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='wall_material',
            field=models.CharField(blank=True, choices=[('block', 'Блочный'), ('panel', 'Панельный'), ('brick', 'Кирпичный'), ('monolithic', 'Монолитный')], max_length=100, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='water_supply',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('yes', 'Есть'), ('hot', 'Горячая'), ('cold', 'Холодная')], max_length=50, verbose_name='Водоснабжение'),
        ),
    ]
