# Generated by Django 5.1 on 2024-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0002_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(verbose_name='Текст сертификата'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
