# Generated by Django 5.1 on 2024-09-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0006_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Изображение сертификата'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сертификата'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
    ]
