# Generated by Django 5.1 on 2024-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0007_companyinfo_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Общая информация о компании'),
        ),
    ]
