# Generated by Django 5.1.2 on 2024-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebPages", "0013_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, max_digits=2, verbose_name="Оценка"
            ),
        ),
    ]
