# Generated by Django 5.0.4 on 2024-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
    ]
