# Generated by Django 5.0.4 on 2024-05-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5', '0003_alter_news_options_alter_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_agent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
