# Generated by Django 5.0.4 on 2024-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab5', '0006_alter_article_image_alter_contact_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
