# Generated by Django 5.1 on 2024-09-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0011_banner_partner_promocode_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate_text',
        ),
    ]
