# Generated by Django 5.1.2 on 2024-11-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0016_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job_description',
            field=models.CharField(max_length=100, verbose_name='Описание выполняемых работ'),
        ),
    ]
