# Generated by Django 5.1 on 2024-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0003_alter_companyinfo_certificate_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компаниях'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
