# Generated by Django 5.1 on 2024-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0004_alter_companyinfo_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
    ]
