# Generated by Django 5.1.2 on 2024-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebPages", "0014_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(verbose_name="Оценка"),
        ),
    ]
