# Generated by Django 5.1.2 on 2024-11-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0015_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo_url', models.URLField(verbose_name='Ссылка на фото')),
                ('job_description', models.TextField(verbose_name='Описание выполняемых работ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
