# Generated by Django 5.1 on 2024-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0009_alter_property_property_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_kind',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид недвижимости'),
        ),
    ]
