# Generated by Django 5.1 on 2024-08-30 20:36

import Properties.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0013_apartment_commercialproperty_garage_house_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='house',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Properties.models.property_directory_path, verbose_name='Фотография')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
