# Generated by Django 5.1 on 2024-08-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0014_remove_apartment_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='building_type',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='balcony',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие балкона/лоджии'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building_section',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков (м)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни (кв. м)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='bathroom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Санузел'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='building_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс здания'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='building_section',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='electricity',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='gas_supply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='has_legal_address',
            field=models.BooleanField(blank=True, default=False, verbose_name='Наличие юридического адреса'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='heating',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='phone_lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество телефонов'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='plot_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='separate_spaces_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Количество раздельных помещений'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажей в здании'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='wall_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='water_supply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='bathroom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Санузел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garage',
            name='building_section',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garage',
            name='ceiling_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='electricity',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Электричество'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='gas_supply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Газоснабжение'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='heating',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='separate_spaces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество раздельных помещений'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='wall_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='water_supply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='house',
            name='building_section',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни (кв. м)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='plot_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка (сотки)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='renovation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='house',
            name='wall_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал стен'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
