# Generated by Django 5.1 on 2024-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Properties', '0020_changerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные изменения'),
        ),
    ]
